### ISSUE TITLE
Precompilation

### ISSUE THREAD

**Issue by jpfairbanks** [yunjhongwu/TensorDecompositions.jl#5]
Thanks for making this helpful package.

Is there a reason that this package doesn't use the precompile feature?
http://docs.julialang.org/en/release-0.4/manual/modules/#module-initialization-and-precompilation.
Was it just not standard as of Dec 2015?

If there is nothing preventing precompilation, I could enable it.

**Comment by yunjhongwu** [comment]
Thank you for the suggestion. I have pushed this change to the `staged` branch. I will merge it to master once Julia 0.5 is out.

**Comment by Gnimuc** [comment]
The doc says:
>'__precompile__()' should not be used in a module unless all of its dependencies are also using '__precompile__()'. Failure to do so can result in a runtime error when loading the module.

Precompilation is not enabled on TensorOperations, so we should not enable it here.

**Comment by yunjhongwu** [comment]
@Gnimuc I have merged your pull request. Thanks!
